[build]
target = "x86_64-unknown-uefi"

[unstable]
build-std = ["core"]

[target.x86_64-unknown-uefi]
rustflags = [
    "-C", "link-arg=/base:0x13370000",
    "-C", "link-arg=/fixed",
    "-C", "link-arg=/debug:dwarf", 
    "-C", "relocation-model=static", 
    "-C", "code-model=small", 
    
]